export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const CATE_GET_SUCCESS = 'CATE_ADD_SUCCESS';

export const PRODUCT_GET_SUCCESS = 'PRODUCT_GET_SUCCESS';

export const IMPORT_PRODUCT_GET_SUCCESS = 'IMPORT_PRODUCT_GET_SUCCESS';

export const EXPORT_PRODUCT_GET_SUCCESS = 'EXPORT_PRODUCT_GET_SUCCESS';