export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const CATE_GET_SUCCESS = 'CATE_ADD_SUCCESS';

export const PRODUCT_GET_SUCCESS = 'PRODUCT_GET_SUCCESS';

export const IMPORT_PRODUCT_GET_SUCCESS = 'IMPORT_PRODUCT_GET_SUCCESS';

export const EXPORT_PRODUCT_GET_SUCCESS = 'EXPORT_PRODUCT_GET_SUCCESS';

export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const DELIVERY_GET_SUCCESS = 'DELIVERY_GET_SUCCESS';
export const ROLE_GET_SUCCESS = 'ROLE_GET_SUCCESS';